.Dd January 18, 2009
.Dt libsmio 3
.Os libsmio
.Sh NAME
.Nm libsmio.h
.Nd Library that provides a Media Storage Input Output (MSIO) abstraction
.Sh LIBRARY
.Lb libsmio
.Sh SYNOPSIS
.In libsmio.h
.Pp
.Ft const char *
.Fn libsmio_get_version "void"
.Ft void
.Fn libsmio_set_notify_values "FILE *stream, uint8_t verbose"
.Ft int
.Fn libsmio_handle_initialize "libsmio_handle_t **handle, int media_storage_type"
.Ft int
.Fn libsmio_handle_free "libsmio_handle_t **handle"
.Ft int
.Fn libsmio_glob "libsmio_handle_t *handle, const char *filename, size_t length, char **filenames[], char **information_filename"
.Ft int
.Fn libsmio_open "libsmio_handle_t *handle, char * const filenames[], int amount_of_filenames, const char *information_filename, int flags"
.Ft ssize_t
.Fn libsmio_read_prepare_buffer "libsmio_handle_t *handle, libsmio_buffer_t *buffer"
.Ft ssize_t
.Fn libsmio_read_buffer "libsmio_handle_t *handle, libsmio_buffer_t *buffer, size_t read_size"
.Ft ssize_t
.Fn libsmio_write_prepare_buffer "libsmio_handle_t *handle, libsmio_buffer_t *buffer"
.Ft ssize_t
.Fn libsmio_write_buffer "libsmio_handle_t *handle, libsmio_buffer_t *buffer, size_t write_size"
.Ft int
.Fn libsmio_close "libsmio_handle_t *handle"

.Pp
When wide character support functions like wmain and wopen are present and libsmio is compiled with
.Ar HAVE_WIDE_CHARACTER_SUPPORT_FUNCTIONS
,
.Ar LIBMSIO_WIDE_CHARACTER_FILE_FUNCTIONS
 is defined in libsmio/types.h and the following functions will replace their narrow character functions.
.Ft int
.Fn libsmio_glob "libsmio_handle_t *handle, const wchar_t *filename, size_t length, wchar_t **filenames[], wchar_t **information_filename"
.Ft int
.Fn libsmio_open "libsmio_handle_t *handle, wchar_t * const filenames[], int amount_of_filenames, const wchar_t *information_filename, int flags"
.Sh DESCRIPTION
The
.Fn libsmio_get_version
function is used to retrieve the library version.
.Pp
The
.Fn libsmio_glob
function globs
.Ar filenames
and the
.Ar information_filename
using the
.Ar filename
and the
.Ar media_storage_type
according to the media storage specific file naming schema.
.Pp
The
.Fn libsmio_open ,
.Fn libsmio_seek_offset ,
.Fn libsmio_read_buffer ,
.Fn libsmio_read_random ,
.Fn libsmio_write_buffer ,
.Fn libsmio_write_random ,
.Fn libsmio_close
functions can be used to open, seek in, read from, write to and close media storage files.

.Sh RETURN VALUES
Most of the functions return NULL or -1 on error, dependent on the return type. For the actual return values refer to libsmio.h
.Sh ENVIRONMENT
None
.Sh FILES
None
.Sh BUGS
Please report bugs of any kind to <forensics@hoffmannbv.nl> or on the project website:
https://www.uitwisselplatform.nl/projects/libsmio/
.Sh AUTHOR
These man pages were written by Joachim Metz.
.Sh COPYRIGHT
Copyright 2008-2009 Joachim Metz, Hoffmann Investigations <forensics@hoffmannbv.nl> and contributors.
This is free software; see the source for copying conditions. There is NO warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
.Sh SEE ALSO
the libsmio.h include file
