.Dd June 27, 2026
.Dt SMRAWMOUNT 1
.Os
.Sh NAME
.Nm smrawmount
.Nd mounts a storage media (split) RAW image file
.Sh SYNOPSIS
.Nm smrawmount
.Op Fl X Ar extended_options
.Op Fl hvV
.Ar sources
.Ar mount_point
.Sh DESCRIPTION
.Nm smrawmount
is a utility to mount a storage media (split) RAW image file
.Pp
.Nm smrawmount
is part of the
.Nm libsmraw
package.
.Nm libsmraw
is a library to access the storage media (SM) (split) RAW format
.Pp
.Ar sources
first or all files of a set of (split) RAW image segment files
.Ar mount_point
the directory to serve as mount point
.Pp
The options are as follows:
.Bl -tag -width Ds
.It Fl h
shows this help
.It Fl v
verbose output to stderr, while smrawmount will remain running in the foreground
.It Fl V
print version
.It Fl X Ar extended_options
extended options to pass to sub system
.El
.Sh ENVIRONMENT
None
.Sh FILES
None
.Sh EXAMPLES
.Bd -literal
# smrawmount image1.raw /mnt/smraw
smrawmount 20260627
.sp
.Ed
.Sh DIAGNOSTICS
Errors, verbose and debug output are printed to stderr when verbose output \
\-v is enabled.
Verbose and debug output are only printed when enabled at compilation.
.Sh AUTHORS
.An Joachim Metz <joachim.metz@gmail.com>
.Sh BUGS
Please report bugs of any kind on the project issue tracker: \
https://github.com/libyal/libsmraw/issues
.Sh COPYRIGHT
Copyright (C) 2010-2026, Joachim Metz <joachim.metz@gmail.com>.
.sp
This is free software; see the source for copying conditions.
There is NO warranty; not even for MERCHANTABILITY or FITNESS FOR A \
PARTICULAR PURPOSE.
